raw_foods:
  tomato:
    value: 10
  onion:
    value: 10


max_num_ingredients: 3

terrain_info:
  tomato:
    placeable: true
    dispenser: true
  onion:
    placeable: true
    dispenser: true
  dish:
    placeable: true
    dispenser: true
  deliver:
    placeable: false
  stove:
    placeable: true
    default_object: "pot"
    activate: ["pot"]
  counter:
    placeable: true
  bin:
    placeable: false

map_to_symbol:
  tomato: "T"
  onion: "O"
  dish: "D"
  deliver: "_"
  stove: "S"
  counter: "X"
  bin: "B"
  floor: " "

object_representation:
  tomato: "†"
  onion: "ø"
  dish: "ⓓ"
  pot: "ⓟ"

container_info:
  dish:
    cook_time: 0
    max_ingredients: 1
    can_add: ["onionsoup", "onion2soup", "tomatosoup", "oniontomatosoup"]
    deliverable: true
  pot:
    cook_time: 30
    max_ingredients: 3
    can_add: ["tomato", "onion"]

recipe_info: [
  ["onion", "pot", "onionsoup"],
  ["onion, onion", "pot", "onion2soup"],
  ["tomato", "pot", "tomatosoup"],
  ["onion, tomato", "pot", "oniontomatosoup"],
]




BASE_REW_SHAPING_PARAMS:
  PLACEMENT_IN_POT_REW: 3
  DISH_PICKUP_REWARD: 3
  SOUP_PICKUP_REWARD: 5
  DISH_DISP_DISTANCE_REW: 0
  POT_DISTANCE_REW: 0
  SOUP_DISTANCE_REW: 0

potential_constants:
  default:
    pot: 10
    move: 10
    add: 10
default_potential:
  onion: 10
  tomato: 10
  onionsoup: 20
  tomatosoup: 20
  oniontomatosoup: 30
default_recipe_value: 17
default_recipe_time: 17