raw_foods: ["tomato", "onion"]
max_num_ingredients: 3

terrain_info:
  tomato:
    symbol: "T"
    placeable: true
    dispenser: true
  onion:
    symbol: "O"
    placeable: true
    dispenser: true
  dish:
    symbol: "D"
    placeable: true
    dispenser: true
  deliver:
    symbol: "_"
  stove:
    symbol: "S"
    placeable: true
    default_object: "pot"
    activate: ["pot"]
  counter:
    symbol: "X"
    placeable: true
  bin:
    symbol: "B"
  floor:
    symbol: " "

object_representation:
  tomato: "†"
  onion: "ø"
  dish: "ⓓ"
  pot: "ⓟ"

container_info:
  dish:
    cook_time: 0
    max_ingredients: 1
    can_add: ["onionsoup", "tomatosoup", "oniontomatosoup"]
    deliverable: true
  pot:
    cook_time: 30
    max_ingredients: 3
    can_add: ["tomato", "onion"]

recipe_info: [
  ["onion", "pot", "onionsoup"],
  ["onion, onion", "pot", "onion2soup"],
  ["tomato", "pot", "tomatosoup"],
  ["onion, tomato", "pot", "oniontomatosoup"],
]




BASE_REW_SHAPING_PARAMS:
  PLACEMENT_IN_POT_REW: 3
  DISH_PICKUP_REWARD: 3
  SOUP_PICKUP_REWARD: 5
  DISH_DISP_DISTANCE_REW: 0
  POT_DISTANCE_REW: 0
  SOUP_DISTANCE_REW: 0

potential_constants:
  default:
    max_delivery_steps: 10
    max_pickup_steps: 10
    pot_onion_steps: 10
    pot_tomato_steps: 10
  mdp_test_tomato:
    max_delivery_steps: 4
    max_pickup_steps: 4
    pot_onion_steps: 5
    pot_tomato_steps: 6
default_potential:
  onion: 10
  tomato: 10
  onionsoup: 20
  tomatosoup: 20
  oniontomatosoup: 30
default_recipe_value: 20
default_recipe_time: 20