raw_foods: ["tomato", "onion"]
containers: ["dish", "pot"]
deliverable_containers: ["dish"]
dispensers: ["tomato", "onion", "dish"]

terrains: ["tomato", "onion", "dish", "deliver", "stove", "counter", "bin"]

default_objects:
  stove: "pot"

max_num_ingredients: 3

object_representation:
  tomato: "†"
  onion: "ø"
  dish: "ⓓ"
  pot: "ⓟ"
terrain_to_symbol:
  tomato: "T"
  onion: "O"
  dish: "D"
  deliver: "_"
  stove: "S"
  counter: "X"
  bin: "B"
  floor: " "

container_info:
  dish:
    cook_time: 0
    max_ingredients: 1
    can_add: ["onionsoup", "tomatosoup", "oniontomatosoup"]
  pot:
    cook_time: 30
    max_ingredients: 3
    can_add: ["tomato", "onion"]
    activate_on: "stove"

station_info:
  stove: ["pot"]

recipe_info: [
  ["onion", "pot", "onionsoup"],
  ["onion, onion", "pot", "onion2soup"],
  ["tomato", "pot", "tomatosoup"],
  ["onion, tomato", "pot", "oniontomatosoup"],
]


BASE_REW_SHAPING_PARAMS:
  PLACEMENT_IN_POT_REW: 3
  DISH_PICKUP_REWARD: 3
  SOUP_PICKUP_REWARD: 5
  DISH_DISP_DISTANCE_REW: 0
  POT_DISTANCE_REW: 0
  SOUP_DISTANCE_REW: 0

potential_constants:
  default:
    max_delivery_steps: 10
    max_pickup_steps: 10
    pot_onion_steps: 10
    pot_tomato_steps: 10
  mdp_test_tomato:
    max_delivery_steps: 4
    max_pickup_steps: 4
    pot_onion_steps: 5
    pot_tomato_steps: 6
default_potential:
  onion: 10
  tomato: 10
  onionsoup: 20
  tomatosoup: 20
  oniontomatosoup: 30
default_recipe_value: 20
default_recipe_time: 20